### ISSUE TITLE
getValidMove for Pawn will fail when no move is made

### ISSUE THREAD

**Issue by gabatree** [capbloo/csc207project#27]
When a board is made at first, the lastmove is set to null. And getValidMove for Pawn will need last move to run. And will throw an error
java.lang.NullPointerException: Cannot invoke "entity.Move.getPieceMoving()" because "lastMove" is null

**Comment by capbloo** [comment]
Thanks for the heads up! This should be fixed with this pull request: https://github.com/capbloo/csc207project/pull/29
